# Generated by Django 4.2.6 on 2024-03-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0042_delete_taskdeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='team.task')),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
    ]
