# Generated by Django 4.2.6 on 2024-03-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_project_time', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
    ]
