# Generated by Django 4.2.6 on 2024-03-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0045_delete_taskdeadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_project_time', '0002_delete_taskdeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline', to='team.task')),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='UserTimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_categories', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(related_name='time_categories', through='user_project_time.TaskDeadline', to='team.task')),
            ],
            options={
                'unique_together': {('employee', 'status')},
            },
        ),
        migrations.AddField(
            model_name='taskdeadline',
            name='time_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='user_project_time.usertimecategory'),
        ),
    ]
