# Generated by Django 4.2.6 on 2024-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_project_time', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertimecategory',
            unique_together=set(),
        ),
    ]
