# Generated by Django 4.2.6 on 2024-03-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_delete_taskdeadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_project_time', '0004_alter_usertimecategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeadline',
            name='status',
            field=models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline', to='team.task', verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='time_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='user_project_time.usertimecategory', verbose_name='Категория срочности'),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец срока'),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало задачи'),
        ),
        migrations.AlterField(
            model_name='usertimecategory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_categories', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='usertimecategory',
            name='status',
            field=models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usertimecategory',
            name='tasks',
            field=models.ManyToManyField(related_name='time_categories', through='user_project_time.TaskDeadline', to='team.task', verbose_name='Задачи'),
        ),
    ]
