# Generated by Django 4.2.6 on 2024-03-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_project_time', '0005_taskdeadline_status_alter_taskdeadline_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdeadline',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskdeadline',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskdeadline',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='taskdeadline',
            name='time_start',
        ),
    ]
