# Generated by Django 4.2.6 on 2023-11-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtasks',
            options={'ordering': ['task_id', 'title']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project_id', 'title']},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='json_with_optional_info',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='counter_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='employees',
            field=models.ManyToManyField(to='team.employee'),
        ),
        migrations.AlterField(
            model_name='company',
            name='json_with_department_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customization',
            name='customisation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.employee'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.employee'),
        ),
        migrations.AlterField(
            model_name='message',
            name='json_with_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='positions',
            name='json_with_optional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='json_info_with_access_level',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='json_with_subtask_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_task_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Work'), (3, 'Inspection'), (4, 'Revision')], default=2),
        ),
        migrations.AlterField(
            model_name='userprojecttask',
            name='json_with_subtask_and_subtask_personal_not',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprojecttask',
            name='task_personal_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprojecttime',
            name='json_with_time_and_name_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LinksResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.employee')),
            ],
        ),
    ]
