# Generated by Django 4.2.6 on 2023-12-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.subtasks')),
            ],
            options={
                'order_with_respect_to': 'subtask_id',
            },
        ),
        migrations.CreateModel(
            name='SubtaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.subtasks')),
            ],
            options={
                'order_with_respect_to': 'subtask_id',
            },
        ),
    ]
