# Generated by Django 4.2.6 on 2023-11-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='json_with_department_info',
        ),
        migrations.RemoveField(
            model_name='company',
            name='json_with_settings_info',
        ),
    ]
