# Generated by Django 4.2.6 on 2023-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_subtaskimage_subtaskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='icon_for_profile.svg', upload_to='images/%Y/%m/%d/%H/'),
        ),
    ]
