# Generated by Django 4.2.6 on 2023-11-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_company_json_with_department_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompany',
            name='json_with_employee_info',
        ),
    ]
