# Generated by Django 4.2.6 on 2023-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_employee_managers_remove_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='json_with_department_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='json_with_settings_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='json_with_employee_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='json_with_content',
            field=models.JSONField(default=dict),
        ),
    ]
