# Generated by Django 4.2.6 on 2023-12-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_subtaskimage_subtaskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='team.task'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_personal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
