# Generated by Django 4.2.6 on 2023-11-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_employeecompany_json_with_employee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_creater',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
