# Generated by Django 4.2.6 on 2023-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H/'),
        ),
    ]
