# Generated by Django 4.2.6 on 2023-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_company_json_with_department_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='json_with_department_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='json_with_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='positions',
            name='json_with_optional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='json_info_with_access_level',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='json_with_subtask_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_task_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprojecttask',
            name='json_with_subtask_and_subtask_personal_not',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprojecttask',
            name='task_personal_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprojecttime',
            name='json_with_time_and_name_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
