# Generated by Django 4.2.6 on 2023-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_project_project_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
