# Generated by Django 4.2.6 on 2023-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksresources',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
