# Generated by Django 4.2.6 on 2023-11-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_task_file_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='files/%Y/%m/%d/%H/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task')),
            ],
        ),
    ]
