# Generated by Django 4.2.6 on 2024-01-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_employee_tasks_userproject_employee_id_and_more'),
        ('team', '0007_linksresources_title'),
    ]

    operations = [
    ]
