# Generated by Django 4.2.6 on 2024-01-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_merge_20231229_1309'),
        ('team', '0008_merge_20240101_2126'),
    ]

    operations = [
    ]
