# Generated by Django 4.2.6 on 2024-01-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_employee_json_with_settings_info'),
        ('team', '0009_merge_20240104_1506'),
    ]

    operations = [
    ]
