# Generated by Django 4.2.6 on 2024-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_merge_20240111_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
