# Generated by Django 4.2.6 on 2024-02-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_merge_20240111_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_with_employee_info', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CompanyEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('company_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.companyevent')),
            ],
            options={
                'order_with_respect_to': 'company_event',
            },
        ),
        migrations.CreateModel(
            name='CompanyEventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/%Y/%m/%d/%H/')),
                ('company_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.companyevent')),
            ],
            options={
                'order_with_respect_to': 'company_event',
            },
        ),
    ]
