# Generated by Django 4.2.6 on 2024-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_employee_json_with_settings_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='team.task'),
        ),
    ]
