# Generated by Django 4.2.6 on 2024-02-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_companyevent_alter_employee_json_with_settings_info_and_more'),
        ('team', '0012_alter_employee_tasks'),
    ]

    operations = [
    ]
