# Generated by Django 4.2.6 on 2024-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_merge_20240204_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
