# Generated by Django 4.2.6 on 2024-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecompany',
            unique_together={('company_id', 'employee_id')},
        ),
    ]
