# Generated by Django 4.2.6 on 2024-02-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyeventfile',
            old_name='image',
            new_name='file',
        ),
    ]
