# Generated by Django 4.2.6 on 2024-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_rename_image_companyeventfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyeventfile',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/%H/'),
        ),
    ]
