# Generated by Django 4.2.6 on 2024-02-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_alter_companyeventfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyevent',
            options={'ordering': ['-time_start']},
        ),
        migrations.RemoveField(
            model_name='companyevent',
            name='date',
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
