# Generated by Django 4.2.6 on 2024-02-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_alter_department_supervisor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecompany',
            unique_together=set(),
        ),
    ]
