# Generated by Django 4.2.6 on 2024-02-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_employeecompany_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('title', 'employee_id')},
        ),
    ]
