# Generated by Django 4.2.6 on 2024-02-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_task_user_project_task_alter_employee_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProject',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='UserProjectTask',
            new_name='Taskboard',
        ),
        migrations.RenameField(
            model_name='taskboard',
            old_name='json_with_subtask_and_subtask_personal_not',
            new_name='json_with_subtask_and_subtask_personal_note',
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='team.task'),
        ),
    ]
