# Generated by Django 4.2.6 on 2024-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_rename_userproject_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='user_project_id',
            new_name='category_id',
        ),
    ]
