# Generated by Django 4.2.6 on 2024-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_companyevent_options_remove_companyevent_date_and_more'),
        ('team', '0025_remove_task_user_project_task_task_user_category'),
    ]

    operations = [
    ]
