# Generated by Django 4.2.6 on 2024-02-15 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0026_merge_20240215_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='employees',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='team.company'),
        ),
        migrations.AlterField(
            model_name='companyeventfile',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='companyeventimage',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='customisation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customization', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='team.company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.department'),
        ),
        migrations.AlterField(
            model_name='linksresources',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='team.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positions',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='team.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='team.company'),
        ),
        migrations.AlterField(
            model_name='subtaskfile',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='subtaskimage',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.project'),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboards', to='team.category'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.task'),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.task'),
        ),
    ]
