# Generated by Django 4.2.6 on 2024-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_alter_category_employee_id_alter_chat_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='companies',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.company'),
        ),
    ]
