# Generated by Django 4.2.6 on 2024-02-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0026_merge_20240215_1936'),
        ('team', '0029_employee_departments_employee_positions'),
    ]

    operations = [
    ]
