# Generated by Django 4.2.6 on 2024-02-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_alter_department_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(blank=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='team.task')),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='UserDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
                ('task_deadline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deadlines', to='team.taskdeadline')),
            ],
            options={
                'ordering': ['employee_id', 'status'],
                'unique_together': {('employee_id', 'task_deadline_id')},
            },
        ),
        migrations.DeleteModel(
            name='UserProjectTime',
        ),
        migrations.AddField(
            model_name='taskdeadline',
            name='user_deadline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_deadlines', to='team.userdeadline'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdeadline',
            unique_together={('task_id', 'user_deadline_id')},
        ),
    ]
