# Generated by Django 4.2.6 on 2024-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_alter_department_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
