# Generated by Django 4.2.6 on 2024-02-26 04:17

from django.db import migrations, models
import team.utils


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0033_employee_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='task_status',
            field=models.JSONField(default=team.utils.get_task_status),
        ),
    ]
