# Generated by Django 4.2.6 on 2024-02-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0033_taskdeadline_userdeadline_delete_userprojecttime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdeadline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskdeadline',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdeadline',
            name='status',
            field=models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9),
        ),
        migrations.RemoveField(
            model_name='taskdeadline',
            name='user_deadline_id',
        ),
    ]
