# Generated by Django 4.2.6 on 2024-02-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0034_alter_taskdeadline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeadline',
            name='status',
            field=models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9),
        ),
        migrations.DeleteModel(
            name='UserDeadline',
        ),
    ]
