# Generated by Django 4.2.6 on 2024-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_task_satus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='satus',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
