# Generated by Django 4.2.6 on 2024-02-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_taskdeadline_status_delete_userdeadline'),
        ('team', '0036_remove_task_satus_task_status'),
    ]

    operations = [
    ]
