# Generated by Django 4.2.6 on 2024-03-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0040_alter_employee_json_with_settings_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
