# Generated by Django 4.2.6 on 2024-03-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0041_remove_message_chat_id_remove_message_employee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
    ]
