# Generated by Django 4.2.6 on 2024-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0043_taskdeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboard',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='taskboard',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Taskboard',
        ),
    ]
