# Generated by Django 4.2.6 on 2024-03-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0044_remove_taskboard_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
    ]
