# Generated by Django 4.2.6 on 2024-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0044_remove_taskboard_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
