# Generated by Django 4.2.6 on 2024-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_delete_taskdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец срока'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало задачи'),
        ),
    ]
