# Generated by Django 4.2.6 on 2024-03-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_alter_task_task_status'),
        ('team', '0047_alter_task_json_with_employee_info_and_more'),
    ]

    operations = [
    ]
