# Generated by Django 4.2.6 on 2024-03-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0048_merge_20240328_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='team.task')),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
    ]
