# Generated by Django 4.2.6 on 2024-03-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0049_remove_task_time_end_remove_task_time_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('json_with_content', models.JSONField(blank=True, default=dict)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.chat')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('project_personal_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('task_personal_notes', models.JSONField(blank=True, default=dict)),
                ('json_with_subtask_and_subtask_personal_not', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProjectTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_with_time_and_name_info', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='online_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Work'), (3, 'Inspection'), (4, 'Revision')], default=2),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company'),
        ),
        migrations.AlterField(
            model_name='companyeventfile',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='companyeventimage',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='customisation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='supervisor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='team.task'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.department'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.positions'),
        ),
        migrations.AlterField(
            model_name='linksresources',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positions',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company'),
        ),
        migrations.AlterField(
            model_name='subtaskfile',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='subtaskimage',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.project'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
        migrations.AddField(
            model_name='userprojecttask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task'),
        ),
        migrations.AddField(
            model_name='userprojecttask',
            name='user_project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.userproject'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
