# Generated by Django 4.2.6 on 2024-03-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.utils


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0050_chat_message_userproject_userprojecttask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9)),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.RemoveField(
            model_name='chat',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='userprojecttask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='userprojecttask',
            name='user_project_id',
        ),
        migrations.DeleteModel(
            name='UserProjectTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='companies',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.positions'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_status',
            field=models.JSONField(default=team.utils.get_task_status),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='team.company'),
        ),
        migrations.AlterField(
            model_name='companyeventfile',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='companyeventimage',
            name='company_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.companyevent'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='customisation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customization', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='team.company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='json_with_settings_info',
            field=models.JSONField(blank=True, default=team.utils.create_base_settings_json_to_employee),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='executors', to='team.task'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='team.company'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='team.department'),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='team.positions'),
        ),
        migrations.AlterField(
            model_name='linksresources',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positions',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='team.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='team.company'),
        ),
        migrations.AlterField(
            model_name='subtaskfile',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='subtaskimage',
            name='subtask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.subtasks'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.project'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.task'),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.task'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
        migrations.DeleteModel(
            name='UserProjectTask',
        ),
        migrations.AddField(
            model_name='taskdeadline',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='team.task'),
        ),
    ]
