# Generated by Django 4.2.6 on 2024-03-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0051_taskdeadline_remove_chat_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец срока'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='json_with_employee_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные об исполнителях'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.task', verbose_name='Родительская задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Задача'),
        ),
        migrations.DeleteModel(
            name='TaskDeadline',
        ),
    ]
