# Generated by Django 4.2.6 on 2024-03-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0053_alter_task_json_with_employee_info_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='linksresources',
            order_with_respect_to=None,
        ),
    ]
