# Generated by Django 4.2.6 on 2024-03-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0054_alter_linksresources_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='linksresources',
            order_with_respect_to='employee_id',
        ),
    ]
