# Generated by Django 4.2.6 on 2024-06-02 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline', to='team.task', verbose_name='Задачи')),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Overtimed', 'Overtimed'), ('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('Week', 'Week'), ('Month', 'Month'), ('Not_soon', 'Not Soon'), ('Permanent', 'Permanent')], default='Permanent', max_length=9, verbose_name='Статус')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_categories', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('tasks', models.ManyToManyField(related_name='time_categories', through='user_project_time.TaskDeadline', to='team.task', verbose_name='Задачи')),
            ],
        ),
        migrations.AddField(
            model_name='taskdeadline',
            name='time_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='user_project_time.usertimecategory', verbose_name='Категория срочности'),
        ),
    ]
