# Generated by Django 4.2.6 on 2024-03-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_delete_taskdeadline'),
        ('user_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskboard',
            unique_together={('category_id', 'task_id')},
        ),
    ]
