# Generated by Django 4.2.6 on 2024-06-02 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('project_personal_notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Работники')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Taskboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Категория')),
                ('task_personal_notes', models.JSONField(blank=True, default=dict, verbose_name='Заметки')),
                ('json_with_subtask_and_subtask_personal_note', models.JSONField(blank=True, default=dict, verbose_name='Подзадачи')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskboards', to='user_project.category', verbose_name='Категория')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.task', verbose_name='Задачи')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('category_id', 'task_id')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tasks',
            field=models.ManyToManyField(related_name='user_category', through='user_project.Taskboard', to='team.task', verbose_name='Задачи'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'employee_id')},
        ),
    ]
