# Generated by Django 4.2.6 on 2024-06-02 10:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import team.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('online_status', models.BooleanField(default=False)),
                ('json_with_settings_info', models.JSONField(blank=True, default=team.utils.create_base_settings_json_to_employee)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H/')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('owner_id', models.IntegerField(help_text='Тут будет храниться id создателя компании(т. е. того человека, который будет платить)')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_with_employee_info', models.JSONField(blank=True, default=dict)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='team.company')),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='team.company')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.department')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('project_creater', models.IntegerField()),
                ('view_counter', models.IntegerField(choices=[(1, 'Absolute'), (2, 'Partial'), (3, 'In_percentages'), (4, 'None_display')], default=4)),
                ('json_info_with_access_level', models.JSONField(blank=True, default=dict)),
                ('task_status', models.JSONField(default=team.utils.get_task_status)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='team.company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True, null=True)),
                ('json_with_employee_info', models.JSONField(blank=True, default=dict)),
                ('task_status', models.CharField(blank=True, max_length=40, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец срока')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='team.task')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='team.project')),
            ],
            options={
                'ordering': ['project_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('customisation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customization', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('color_scheme', models.CharField(default='', max_length=40)),
                ('font_size', models.CharField(default='', max_length=40)),
                ('background', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True, null=True)),
                ('status_yes_no', models.BooleanField(default=False)),
                ('json_with_employee_info', models.JSONField(blank=True, default=dict)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='team.task')),
            ],
            options={
                'ordering': ['task_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('weight', models.SmallIntegerField(choices=[(1, 'Full access'), (2, 'Partial access'), (3, 'Observer')], default=2)),
                ('json_with_optional_info', models.JSONField(blank=True, default=dict)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='team.company')),
            ],
            options={
                'unique_together': {('company_id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='team.company')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='team.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='team.positions')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('company_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.companyevent')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/%H/')),
                ('company_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.companyevent')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='companies',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(related_name='employees', through='team.EmployeeCompany', to='team.positions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='executors', to='team.task'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.task')),
            ],
            options={
                'order_with_respect_to': 'task_id',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='files/%Y/%m/%d/%H/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.task')),
            ],
            options={
                'order_with_respect_to': 'task_id',
            },
        ),
        migrations.CreateModel(
            name='SubtaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.subtasks')),
            ],
            options={
                'order_with_respect_to': 'subtask_id',
            },
        ),
        migrations.CreateModel(
            name='SubtaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d/%H/')),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.subtasks')),
            ],
            options={
                'order_with_respect_to': 'subtask_id',
            },
        ),
        migrations.CreateModel(
            name='LinksResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'employee_id',
            },
        ),
        migrations.AddIndex(
            model_name='employeecompany',
            index=models.Index(fields=['company_id', 'employee_id'], name='team_employ_company_87227e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company_id', 'title')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='companyeventimage',
            order_with_respect_to='company_event',
        ),
        migrations.AlterOrderWithRespectTo(
            name='companyeventfile',
            order_with_respect_to='company_event',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('password', 'username')},
        ),
    ]
